on:
  push:
  #pull_request:
  #  branches: 
  #  - master
  #  types: [ closed ]

name: Upload Release Assets

jobs:
  build:
    name: Upload Release Asset
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - id: semver 
        uses: brpaz/action-semantic-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - run: echo "$OUTPUTS"
        env:
          OUTPUTS: ${{ toJson(steps.semantic.outputs) }}

      # Substitute the Manifest and Download URLs in the module.json
      #- name: Substitute Manifest and Download Links For Versioned Ones
      #  id: sub_manifest_link_version
      #  uses: microsoft/variable-substitution@v1
      #  with:
      #    files: 'module.json'
      #  env:
      #    version: ${{ steps.get_version.outputs.VERSION_NUMBER }}
      #    manifest: https://github.com/${{github.repository}}/releases/download/latest/module.json
      #    download: https://github.com/${{github.repository}}/releases/download/${{steps.semver.outputs.semver_tag}}/${{steps.semver.outputs.semver_tag}}.zip
          
      # Create a release for this specific version
      #- name: Create Release
      #  id: create_version_release
      #  uses: ncipollo/release-action@v1
      #  with:
      #    tag: ${{steps.semver.outputs.semver_tag}}
      #    name: Release ${{steps.semver.outputs.semver_tag}}
      #    draft: false
      #    prerelease: false
      #    token: ${{ secrets.GITHUB_TOKEN }}
      #    artifacts: './module.json,'
