on:
  push:
    branches:
      - 'master'

name: Upload Release Assets

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: |
            echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
            echo ::set-output name=VERSION_NUMBER::${GITHUB_REF/refs\/tags\/v/}

      #Substitute the Manifest and Download URLs in the module.json
      - name: Substitute Manifest and Download Links For Versioned Ones
        id: sub_manifest_link_version
        uses: microsoft/variable-substitution@v1
        with:
          files: 'module.json'
        env:
          version: ${{ steps.get_version.outputs.VERSION_NUMBER }}
          manifest: https://github.com/${{github.repository}}/releases/download/latest/module.json
          download: https://github.com/${{github.repository}}/releases/download/${{steps.get_version.outputs.VERSION}}/pf2e-botd-ex.zip

      - name: Zip files
        run: zip -r pf2e-botd-ex * -x ".github/*"

     # Create a release for this specific version
      - name: Create Release
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.get_version.outputs.VERSION }}
          name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './module.json,./pf2e-botd-ex.zip'
